---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader
  namespace: test
---
apiVersion: v1
kind: Secret
metadata:
  name: reader
  namespace: test
  annotations:
    kubernetes.io/service-account.name: reader
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reader
  namespace: test
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "get"
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reader
subjects:
- kind: ServiceAccount
  name: reader
  namespace: test
