# https://docs.docker.com/compose/compose-file

volumes:
  vscode_config:
  vscode_project:

services:

  vscode:
    build:
      context: vscode
    command:
    - --auth
    - none
    - --proxy-domain
    - vscode.${DOMAIN:?You must supply DOMAIN}
    - --disable-telemetry
    environment:
      GIT_USER: "${GIT_USER}"
      GIT_EMAIL: "${GIT_EMAIL}"
      GIT_CRED: "${GIT_CRED}"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - vscode_config:/home/coder/.config
    - vscode_project:/home/coder/project
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      traefik.enable: "true"
      # Service port
      traefik.http.services.vscode.loadbalancer.server.port: 8080
      # Redirection to HTTPS
      traefik.http.routers.vscode.entrypoints: http
      traefik.http.routers.vscode.rule: Host(`vscode.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.vscode.service: vscode
      traefik.http.routers.vscode.middlewares: redirect-to-https
      # Authenticated endpoint
      traefik.http.routers.vscode-s.entrypoints: https
      traefik.http.routers.vscode-s.rule: Host(`vscode.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.vscode-s.service: vscode
      traefik.http.routers.vscode-s.middlewares: seat-auth
      traefik.http.routers.vscode-s.tls: "true"
