pipeline:

  base:
    image: docker:28.2.2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag registry:5000/groot/base .
    - docker push registry:5000/groot/base

  derived:
    image: docker:28.2.2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag registry:5000/groot/derived .
    - docker push registry:5000/groot/derived