pipeline:

  build:
    image: openjdk:24-jdk
    commands:
    - javac HelloWorld.java
    - jar -cvf HelloWorld.jar HelloWorld.class

  store:
    image: registry:5000/groot/tools
    commands:
    - curl --fail --upload-file HelloWorld.jar -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/${CI_REPO_NAME}/${CI_BUILD_NUMBER}/
    - echo -n ${CI_BUILD_NUMBER} > latest
    - curl --fail --upload-file latest -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/${CI_REPO_NAME}/
    secrets: [ WEBDAV_USER, WEBDAV_PASS ]

  trigger:
    image: plugins/downstream
    server: https://ci.go-nerd.de
    fork: true
    repositories:
      - groot/package
    secrets: [ downstream_token ]