pipeline:
  build:
    image: docker:28.3.2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag registry:5000/groot/frontend .
    - docker push registry:5000/groot/frontend