pipeline:
  build:
    image: docker:27.3
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag registry:5000/groot/frontend .
    - docker push registry:5000/groot/frontend

  trigger:
    image: plugins/downstream
    server: https://ci.go-nerd.de
    fork: true
    repositories:
      - groot/fan-in
    secrets: [ downstream_token ]