services:

  nginx:
    build:
      context: nginx
    environment:
      DOMAIN: ${DOMAIN}
    labels:
      traefik.enable: "true"
      # Authentication
      traefik.http.middlewares.seat1-code.basicauth.users: ${SEAT1_CODE_HTPASSWD}
      traefik.http.middlewares.seat2-code.basicauth.users: ${SEAT2_CODE_HTPASSWD}
      traefik.http.middlewares.seat3-code.basicauth.users: ${SEAT3_CODE_HTPASSWD}
      traefik.http.middlewares.seat4-code.basicauth.users: ${SEAT4_CODE_HTPASSWD}
      traefik.http.middlewares.seat5-code.basicauth.users: ${SEAT5_CODE_HTPASSWD}
      traefik.http.middlewares.seat6-code.basicauth.users: ${SEAT6_CODE_HTPASSWD}
      traefik.http.middlewares.seat7-code.basicauth.users: ${SEAT7_CODE_HTPASSWD}
      traefik.http.middlewares.seat8-code.basicauth.users: ${SEAT8_CODE_HTPASSWD}
      traefik.http.middlewares.seat9-code.basicauth.users: ${SEAT9_CODE_HTPASSWD}
      traefik.http.middlewares.seat10-code.basicauth.users: ${SEAT10_CODE_HTPASSWD}
      traefik.http.middlewares.seat11-code.basicauth.users: ${SEAT11_CODE_HTPASSWD}
      traefik.http.middlewares.seat12-code.basicauth.users: ${SEAT12_CODE_HTPASSWD}
      traefik.http.middlewares.seat13-code.basicauth.users: ${SEAT13_CODE_HTPASSWD}
      traefik.http.middlewares.seat14-code.basicauth.users: ${SEAT14_CODE_HTPASSWD}
      traefik.http.middlewares.seat15-code.basicauth.users: ${SEAT15_CODE_HTPASSWD}
      traefik.http.middlewares.seat16-code.basicauth.users: ${SEAT16_CODE_HTPASSWD}
      traefik.http.middlewares.seat17-code.basicauth.users: ${SEAT17_CODE_HTPASSWD}
      traefik.http.middlewares.seat18-code.basicauth.users: ${SEAT18_CODE_HTPASSWD}
      traefik.http.middlewares.seat19-code.basicauth.users: ${SEAT19_CODE_HTPASSWD}
      traefik.http.middlewares.seat20-code.basicauth.users: ${SEAT20_CODE_HTPASSWD}
      traefik.http.middlewares.seat21-code.basicauth.users: ${SEAT21_CODE_HTPASSWD}
      # Service port
      traefik.http.services.nginx.loadbalancer.server.port: 80
      # Redirection to HTTPS
      traefik.http.routers.nginx.entrypoints: http
      traefik.http.routers.nginx.rule: Host(`${DOMAIN}`)
      traefik.http.routers.nginx.service: nginx
      traefik.http.routers.nginx.middlewares: redirect-to-https
      # Unauthenticated endpoint
      traefik.http.routers.nginx-s.entrypoints: https
      traefik.http.routers.nginx-s.rule: Host(`${DOMAIN}`)
      traefik.http.routers.nginx-s.service: nginx
      traefik.http.routers.nginx-s.tls: "true"
      # Authenticated endpoint
      traefik.http.routers.auth-s.entrypoints: https
      traefik.http.routers.auth-s.rule: Host(`${DOMAIN}`) && PathPrefix(`/seat${INDEX}/`)
      traefik.http.routers.auth-s.service: nginx
      traefik.http.routers.auth-s.tls: "true"
      traefik.http.routers.auth-s.middlewares: seat${INDEX}-code
      # Redirection to HTTPS for dev
      traefik.http.routers.dev.entrypoints: http
      traefik.http.routers.dev.rule: Host(`*.dev.${DOMAIN}`)
      traefik.http.routers.dev.service: nginx
      traefik.http.routers.dev.middlewares: redirect-to-https
      # Authenticated endpoint for dev
      traefik.http.routers.dev-s.entrypoints: https
      traefik.http.routers.dev-s.rule: Host(`*.dev.${DOMAIN}`)
      traefik.http.routers.dev-s.service: nginx
      traefik.http.routers.dev-s.tls: "true"
      # Redirection to HTTPS for live
      traefik.http.routers.live.entrypoints: http
      traefik.http.routers.live.rule: Host(`*.live.${DOMAIN}`)
      traefik.http.routers.live.service: nginx
      traefik.http.routers.live.middlewares: redirect-to-https
      # Authenticated endpoint for live
      traefik.http.routers.live-s.entrypoints: https
      traefik.http.routers.live-s.rule: Host(`*.live.${DOMAIN}`)
      traefik.http.routers.live-s.service: nginx
      traefik.http.routers.live-s.tls: "true"