# https://docs.docker.com/compose/compose-file

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:

services:

  # https://doc.traefik.io/traefik/
  traefik:
    image: traefik:v2.10.5
    command:
    - --log=true
    - --log.level=DEBUG
    - --api=true
    - --api.dashboard=true
    - --entrypoints.http.address=:80
    - --entrypoints.https.address=:443
    - --entrypoints.ssh.address=:2222
    - --providers.file.directory=/etc/traefik/conf.d
    - --providers.docker=true
    - --providers.docker.exposedByDefault=false
    ports:
    - 2222:2222
    - 80:80
    - 443:443
    volumes:
    - ./traefik.d:/etc/traefik/conf.d:ro
    - /etc/ssl:/etc/traefik/ssl:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "netstat -tunapl | grep LISTEN | grep :80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      traefik.enable: "true"
      # Global redirection middleware
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      # traefik dashboard: redirection to HTTPS
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: Host(`traefik.${DOMAIN}`)
      traefik.http.routers.traefik.middlewares: redirect-to-https
      # traefik dashboard: authenticated endpoint
      traefik.http.routers.traefik-s.entrypoints: https
      traefik.http.routers.traefik-s.service: api@internal
      traefik.http.routers.traefik-s.rule: Host(`traefik.${DOMAIN}`)
      traefik.http.routers.traefik-s.tls: "true"
      # TODO: Fix auth
      #traefik.http.routers.traefik-s.middlewares: seat-auth

  # https://docs.gitlab.com/ee/install/docker.html
  gitlab:
    image: gitlab/gitlab-ce:16.5.1-ce.0
    environment:
      # https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Europe/Berlin'

        gitlab_rails['initial_root_password'] = "${GITLAB_ADMIN_PASS}"

        gitlab_rails['usage_ping_enabled'] = false

        external_url 'https://gitlab.${DOMAIN}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['real_ip_trusted_addresses'] = [ '172.16.0.0/12' ]
        nginx['real_ip_header'] = 'X-Real-Ip'
        nginx['real_ip_recursive'] = 'on'
        letsencrypt['enable'] = false

        gitlab_pages['enable'] = true
        pages_external_url 'https://gitlab.${DOMAIN}'
        pages_nginx['listen_https'] = false
        # Required due to https://gitlab.com/gitlab-org/gitlab-pages/issues/129
        gitlab_pages['inplace_chroot'] = true
        # Set listen-proxy when behind reverse proxy. see https://docs.gitlab.com/ee/administration/pages/#configure-listener-for-reverse-proxy-requests
        gitlab_pages['listen_proxy'] = "0.0.0.0:8090"
        # Fix for https://gitlab.com/gitlab-org/gitlab-pages/-/issues/534
        gitlab_pages['internal_gitlab_server'] = "http://127.0.0.1"

        registry_external_url 'https://gitlab.${DOMAIN}'
        registry['registry_http_addr'] = "0.0.0.0:5000"
        registry_nginx['listen_https'] = false

        # Prevent conflict with host SSH port
        gitlab_rails['gitlab_shell_ssh_port'] = 2222

        grafana['alerting_enabled'] = true
        # Fix for chicken-and-egg issue with oauth
        grafana['disable_login_form'] = false
    # https://docs.gitlab.com/ee/install/docker.html#devshm-mount-not-having-enough-space-in-docker-container
    shm_size: 256m
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - gitlab_config:/etc/gitlab
    - gitlab_logs:/var/log/gitlab
    - gitlab_data:/var/opt/gitlab
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      # Web UI: service port
      traefik.http.services.www.loadbalancer.server.port: 80
      # Web UI: redirection to HTTPS
      traefik.http.routers.www.entrypoints: http
      traefik.http.routers.www.rule: Host(`gitlab.${DOMAIN}`)
      traefik.http.routers.www.service: www
      traefik.http.routers.www.middlewares: redirect-to-https
      # Web UI: unauthenticated endpoint
      traefik.http.routers.www-s.entrypoints: https
      traefik.http.routers.www-s.rule: Host(`gitlab.${DOMAIN}`)
      traefik.http.routers.www-s.service: www
      traefik.http.routers.www-s.tls: "true"
      # Pages: service port
      traefik.http.services.pages.loadbalancer.server.port: 8090
      # Pages: redirection to HTTPS
      traefik.http.routers.pages.entrypoints: http
      traefik.http.routers.pages.middlewares: redirect-to-https
      traefik.http.routers.pages.rule: HostRegexp(`{subdomain:.+}.gitlab.${DOMAIN}`)
      traefik.http.routers.pages.service: pages
      # Pages: unauthenticated endpoint
      traefik.http.routers.pages-s.entrypoints: https
      traefik.http.routers.pages-s.rule: HostRegexp(`{subdomain:.+}.gitlab.${DOMAIN}`)
      traefik.http.routers.pages-s.service: pages
      traefik.http.routers.pages-s.tls: "true"
      # Registry: service port
      traefik.http.services.registry.loadbalancer.server.port: 5000
      # Registry: Unauthenticated endpoint
      traefik.http.routers.registry-s.entrypoints: https
      traefik.http.routers.registry-s.rule: HostRegexp(`gitlab.${DOMAIN}`) && PathPrefix(`/v2`)
      traefik.http.routers.registry-s.service: registry
      traefik.http.routers.registry-s.tls: "true"
      # SSH: service port
      traefik.tcp.services.ssh.loadbalancer.server.port: 22
      # SSH: TLS passthrough
      traefik.tcp.routers.ssh.entrypoints: ssh
      traefik.tcp.routers.ssh.rule: HostSNI(`*`)
      traefik.tcp.routers.ssh.service: ssh
      traefik.tcp.routers.ssh.tls.passthrough: "true"
