# https://docs.docker.com/compose/compose-file

services:

  runner:
    build:
      context: $PWD
    environment:
      CI_SERVER_TOKEN: ${CI_SERVER_TOKEN:?You must supply CI_SERVER_TOKEN}
      CI_SERVER_URL: ${CI_SERVER_URL}
      RUNNER_EXECUTOR: ${RUNNER_EXECUTOR:-shell}
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock
