# https://docs.docker.com/compose/compose-file

services:

  kroki:
    image: yuzutech/kroki:0.26.0
    environment:
      KROKI_BLOCKDIAG_HOST: blockdiag
      KROKI_MERMAID_HOST: mermaid
      KROKI_BPMN_HOST: bpmn
      KROKI_EXCALIDRAW_HOST: excalidraw

  blockdiag:
    image: yuzutech/kroki-blockdiag:0.21.3

  mermaid:
    image: yuzutech/kroki-mermaid:0.25.0

  bpmn:
    image: yuzutech/kroki-bpmn:0.26.0

  excalidraw:
    image: yuzutech/kroki-excalidraw:0.26.0
