pipeline:

  build:
    image: openjdk:24-jdk
    commands:
    - javac HelloWorld.java
    - jar -cvf HelloWorld.jar HelloWorld.class

  store:
    image: registry:5000/groot/tools
    commands:
    - curl --fail --upload-file HelloWorld.jar -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/
    secrets: [ WEBDAV_USER, WEBDAV_PASS ]