---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dex
  namespace: dex
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`dex.inmylab.de`)
    services:
    - name: dex
      port: 5556
  tls:
    secretName: certificate-dex
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: dex
  namespace: dex
spec:
  endpoints:
  - dnsName: dex.inmylab.de
    recordTTL: 120
    recordType: CNAME
    targets:
    - lb.inmylab.de
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex
  namespace: dex
spec:
  commonName: dex.inmylab.de
  dnsNames:
  - dex.inmylab.de
  duration: 2160h
  isCA: false
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h
  secretName: certificate-dex
  usages:
  - server auth
  - client auth
