# https://docs.docker.com/compose/compose-file

services:

  # https://docs.gitlab.com/ee/install/docker.html
  vscode:
    image: codercom/code-server:4.18.0
    #volumes:
    #- /root/.config:/home/coder/.config
    #- ${PWD}:/home/coder/project
    user: root
    environment:
      DOCKER_USER: root
    labels:
      traefik.enable: "true"
      traefik.http.services.vscode.loadbalancer.server.port: 8080
      traefik.http.routers.vscode.entrypoints: http
      traefik.http.routers.vscode.rule: Host(`vscode.${DOMAIN:?You must supply DOMAIN}`) || Host(`vscode.${IP:?You must supply IP}.nip.io`)
      traefik.http.routers.vscode.service: vscode
