{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Images",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (image_id) (vuln_operator_cves))"
    }
   ]
  },
  {
   "title": "CVEs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(vuln_operator_cves)" }
   ]
  },
  {
   "title": "Packages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (package) (vuln_operator_cves))"
    }
   ]
  },
  {
   "title": "Count by image",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count by (image_id) (vuln_operator_cves)",
     "legendFormat": "{{.image_id}}"
    }
   ]
  },
  {
   "title": "Count by severity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count by (severity) (vuln_operator_cves)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count by package",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "count by (package, version) (vuln_operator_cves)",
     "legendFormat": "{{package}}@{{version}}"
    }
   ]
  }
 ]
}