apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring
  labels:
    app: monitoring
data:
  telegraf.conf: |
    [global_tags]
    [agent]
    hostname = "$HOSTNAME"
    [[outputs.influxdb]]
    urls = ["$MONITOR_HOST"]
    database = "$MONITOR_DATABASE"
    retention_policy = "autogen"
    timeout = "5s"
    username = "$MONITOR_USERNAME"
    password = "$MONITOR_PASSWORD"
    [[inputs.cpu]]
    percpu = false
    totalcpu = true
    collect_cpu_time = false
    report_active = false
    [[inputs.disk]]
    ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
    [[inputs.diskio]]
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.processes]]
    [[inputs.swap]]
    [[inputs.system]]
    [[inputs.kubernetes]]
    url = "https://$HOSTNAME:10250"
    insecure_skip_verify = true
    bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring
  labels:
    app: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      name: monitoring
      labels:
        app: monitoring
    spec:
      serviceAccountName: default
      restartPolicy: Always
      containers:
      - name: telegraf
        image: telegraf:1.32.0
        imagePullPolicy: Always
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: HOST_PROC
          value: /rootfs/proc
        - name: HOST_SYS
          value: /rootfs/sys
        - name: MONITOR_USERNAME
          valueFrom:
            secretKeyRef:
              key: monitor_username
              name: monitoring
        - name: MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monitor_password
              name: monitoring
        - name: MONITOR_HOST
          valueFrom:
            secretKeyRef:
              key: monitor_host
              name: monitoring
        - name: MONITOR_DATABASE
          valueFrom:
            secretKeyRef:
              key: monitor_database
              name: monitoring
        volumeMounts:
        #- name: sys
        #  mountPath: /rootfs/sys
        #  readOnly: true
        - name: proc
          mountPath: /rootfs/proc
          readOnly: true
        - name: config
          mountPath: /etc/telegraf
      volumes:
      #- name: sys
      #  hostPath:
      #    path: /sys
      #    type: ""
      - name: proc
        hostPath:
          path: /proc
          type: ""
      - name: config
        configMap:
          defaultMode: 420
          name: monitoring
