cluster:
  name: ploayground
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-us-central1.grafana.net/api/prom/push
    auth:
      type: basic
      username: "2160149"
      password: ${GRAFANA_CLOUD_TOKEN}
  - name: grafana-cloud-logs
    type: loki
    url: https://logs-prod-017.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: "497002"
      password: ${GRAFANA_CLOUD_TOKEN}
  - name: grafana-cloud-traces
    type: otlp
    url: https://tempo-us-central1.grafana.net:443
    protocol: grpc
    auth:
      type: basic
      username: "493514"
      password: ${GRAFANA_CLOUD_TOKEN}
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
  - name: grafana-cloud-profiles
    type: pyroscope
    url: https://profiles-prod-003.grafana.net:443
    auth:
      type: basic
      username: "132323"
      password: ${GRAFANA_CLOUD_TOKEN}
clusterMetrics:
  enabled: true
  opencost:
    enabled: false
  kepler:
    enabled: false
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
clusterEvents:
  enabled: true
nodeLogs:
  enabled: true
podLogs:
  enabled: true
applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
autoInstrumentation:
  enabled: true
profiling:
  enabled: true
integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-singleton
            - alloy-logs
            - alloy-receiver
            - alloy-profiles
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true
alloy-logs:
  enabled: true
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
alloy-profiles:
  enabled: true