---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: traefik-dashboard
spec:
  endpoints:
  - dnsName: ${DNS_NAME}
    recordTTL: 300
    recordType: CNAME
    targets:
    - lb.seat0.inmylab.de
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard
spec:
  secretName: traefik-dashboard
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - ${DNS_NAME}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
  - https
  routes:
  - match: Host(`${DNS_NAME}`)
    kind: Rule
    services:
    - name: traefik-dashboard
      port: 80
      strategy: RoundRobin
  tls:
    secretName: traefik-dashboard
