---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
  #disableDefaultCNI: true
  kubeProxyMode: nftables
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: 0.0.0.0
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    listenAddress: 0.0.0.0
    protocol: TCP
