---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-annotations
  labels:
    app: nginx
    version: "1"
  # Annotationen gehören zu den Metadaten
  annotations:
    ci: gitlab
    deployment: "1"
spec:
  containers:
  - name: nginx
    image: nginx
