---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-labels-1
  labels:
    app: nginx
    version: "1"
spec:
  containers:
  - name: nginx
    image: nginx:1.23
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-labels-2
  labels:
    app: nginx
    version: "2"
spec:
  containers:
  - name: nginx
    image: nginx:1.14
---
apiVersion: v1
kind: Pod
metadata:
  name: apache-labels-1
  labels:
    app: apache
    version: "1"
spec:
  containers:
  - name: apache
    image: httpd:2.4