pipeline:

  fetch:
    image: registry:5000/groot/tools
    commands:
    - LATEST=$(curl --fail --user "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/groot/artifact/latest)
    - curl --fail --user "$${WEBDAV_USER}:$${WEBDAV_PASS}" -o HelloWorld.jar https://webdav.dille.io/groot/artifact/$${LATEST}/HelloWorld.jar
    secrets: [ WEBDAV_USER, WEBDAV_PASS ]

  docker:
    image: docker:27.3.1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - REGISTRY=registry:5000
    commands:
    - ls -l
    - docker build --tag registry:5000/groot/package .
    - docker push registry:5000/groot/package