---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
  template:
    metadata:
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.2
        ports:
        - name: http
          containerPort: 80
      volumes:
      - name: config-volume
        configMap:
          name: my-cm
