apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: my-app

generatorOptions:
  disableNameSuffixHash: true

namespace: my-app-namespace

labels:
- pairs:
    owner: me
- pairs:
    app: my-app
  includeSelectors: true

secretGenerator:
- name: my-secret
  type: Opaque
  envs:
  - .env

configMapGenerator:
- name: my-cm
  literals:
  - foo=bar
  - baz=blarg

images:
- name: nginx
  newName: nginx
  newTag: "1.27"

replicas:
- name: my-deployment
  count: 5

resources:
- deployment.yaml
- service.yaml
