pipeline:

  fetch:
    image: registry:5000/groot/tools
    commands:
    - LATEST=$(curl --fail --user "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/groot/hello-world/latest)
    - curl --fail --user "$${WEBDAV_USER}:$${WEBDAV_PASS}" -o HelloWorld.jar https://webdav.dille.io/groot/hello-world/$${LATEST}/HelloWorld.java
    secrets: [ WEBDAV_USER, WEBDAV_PASS ]

  package:
    image: openjdk:25-jdk
    commands:
    - jar -cvf HelloWorld.jar HelloWorld.class

  store:
    image: registry:5000/groot/tools
    commands:
    - curl --fail --upload-file HelloWorld.jar -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/${CI_REPO_NAME}/${CI_BUILD_NUMBER}/
    - echo -n ${CI_BUILD_NUMBER} > latest
    - curl --fail --upload-file latest -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/${CI_REPO_NAME}/
    secrets: [ WEBDAV_USER, WEBDAV_PASS ]