---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir
data:
  mimir.yaml: |
    target: all

    # Configure Mimir to use Minio as object storage backend.
    common:
      storage:
        backend: s3
        s3:
          endpoint: minio.minio:9000
          access_key_id: minioadmin
          secret_access_key: minioadmin
          insecure: true
          bucket_name: mimir

    # Blocks storage requires a prefix when using a common object storage bucket.
    blocks_storage:
      storage_prefix: blocks
      tsdb:
        dir: /data/ingester

    ruler:
      rule_path: /data/ruler
      alertmanager_url: http://127.0.0.1:8080/alertmanager
      ring:
        # Quickly detect unhealthy rulers to speed up the tutorial.
        heartbeat_period: 2s
        heartbeat_timeout: 10s

    server:
      log_level: warn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
spec:
  containers:
  - name: mimir
    image: grafana/mimir:3.0.4
    args:
    - -config.file=/etc/mimir.yaml
    volumeMounts:
    - mountPath: /etc/mimir.yaml
      name: mimir
    - mountPath: /data
      name: data
  volumes:
  - name: config
    configMap:
      name: mimir
  - name: data
    emptyDir: {}
