---
apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  # Container teilen sich den Netzwerk-Namespace
  # Jeder Port nur durch einen Container nutzbar
  containers:
  - name: nginx
    image: nginx:1.27.2
  - name: apache
    image: httpd:2.4.62
