---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  endpoints:
  - dnsName: traefik.inmylab.de
    recordTTL: 120
    recordType: CNAME
    targets:
    - lb.inmylab.de
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  commonName: traefik.inmylab.de
  dnsNames:
  - traefik.inmylab.de
  duration: 2160h
  isCA: false
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h
  secretName: certificate-traefik-dashboard
  usages:
  - server auth
  - client auth
