version: "3.7"

services:

  traefik:
    image: traefik:v3.2.1
    command:
    - --log=true
    - --log.level=DEBUG
    - --accesslog=true
    - --accesslog.fields.names.StartUTC=drop
    - --api=true
    - --api.insecure=true
    - --api.dashboard=true
    - --ping=true
    - --entrypoints.http.address=:80
    - --entrypoints.metrics.address=:8082
    - --providers.docker=true
    - --providers.docker.exposedByDefault=false
    - --metrics.prometheus=true
    - --metrics.prometheus.addEntryPointsLabels=true
    - --metrics.prometheus.addServicesLabels=true
    - --metrics.prometheus.entrypoint=metrics
    ports:
    - 80:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.rule: HostRegexp(`traefik.{domain:[a-z0-9]+}.inmylab.de`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))

  registry:
    image: registry:2.8.3
    ports:
    - "127.0.0.1:5000:5000"
    labels:
      traefik.enable: "true"
      traefik.http.services.registry.loadbalancer.server.port: 5000
      traefik.http.routers.registry.rule: HostRegexp(`registry.{domain:[a-z0-9]+}.inmylab.de`) && PathPrefix(`/v2`)
      traefik.http.routers.registry.entrypoints: http

  dind:
    image: docker:27.5.1-dind
    privileged: true
    network_mode: service:registry

  web:
    image: konradkleine/docker-registry-frontend:v2
    depends_on:
    - registry
    environment:
      ENV_DOCKER_REGISTRY_HOST: "registry"
      ENV_DOCKER_REGISTRY_PORT: 5000
    labels:
      traefik.enable: "true"
      traefik.http.services.web.loadbalancer.server.port: 80
      traefik.http.routers.web.rule: HostRegexp(`hub.{domain:[a-z0-9]+}.inmylab.de`)
      traefik.http.routers.web.entrypoints: http
