# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# https://docs.docker.com/compose/compose-file

configs:
  default_certificate.yaml:
    content: |
      tls:
        stores:
          default:
            defaultCertificate:
              certFile: /etc/traefik/ssl/tls.crt
              keyFile: /etc/traefik/ssl/tls.key

volumes:
  traefik-config:

services:

  traefik-prepare-config:
    image: alpine
    entrypoint:
    - sh
    - -c
    command:
    - cp /etc-traefik-conf.d/default_certificate.yaml /etc/traefik/conf.d/
    configs:
    - source: default_certificate.yaml
      target: /etc-traefik-conf.d/default_certificate.yaml
    volumes:
    - traefik-config:/etc/traefik/conf.d
    restart: no

  # https://doc.traefik.io/traefik/
  traefik:
    image: traefik:v3.6.12
    command:
    - --log=true
    - --log.level=DEBUG
    - --api=true
    - --api.dashboard=true
    - --entrypoints.http.address=:80
    - --entrypoints.https.address=:443
    - --providers.file.directory=/etc/traefik/conf.d
    - --providers.docker=true
    - --providers.docker.exposedByDefault=false
    ports:
    - 80:80
    - 443:443
    volumes:
    - traefik-config:/etc/traefik/conf.d:rw
    - /etc/ssl:/etc/traefik/ssl:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      traefik-prepare-config:
        required: true
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "netstat -tunapl | grep LISTEN | grep :80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      traefik.enable: "true"
      # Global redirection middleware
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      # Auth
      traefik.http.middlewares.traefik-auth.basicauth.users: ${TRAEFIK_HTPASSWD?Environment variable TRAEFIK_HTPASSWD is mandatory}
      # traefik dashboard: redirection to HTTPS
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: Host(`traefik.seat${SEAT_INDEX}.${DOMAIN?Environment variable DOMAIN is mandatory}`)
      traefik.http.routers.traefik.middlewares: redirect-to-https
      # traefik dashboard: authenticated endpoint
      traefik.http.routers.traefik-s.entrypoints: https
      traefik.http.routers.traefik-s.service: api@internal
      traefik.http.routers.traefik-s.rule: Host(`traefik.seat${SEAT_INDEX}.${DOMAIN?Environment variable DOMAIN is mandatory}`)
      traefik.http.routers.traefik-s.middlewares: traefik-auth
      traefik.http.routers.traefik-s.tls: "true"

  vscode:
    image: codercom/code-server:4.115.0
    command:
    - --auth=password
    - --proxy-domain=vscode.seat${SEAT_INDEX}.${DOMAIN?Environment variable DOMAIN is mandatory}
    - --disable-telemetry
    - --disable-update-check
    - --locale=de
    #- --install-extension=PUBLISHER/NAME@VERSION
    environment:
      PASSWORD: "${VSCODE_PASSWORD?Missing VSCODE_PASSWORD environment variable}"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      traefik.enable: "true"
      # Service port
      traefik.http.services.vscode.loadbalancer.server.port: 8080
      # Redirection to HTTPS
      traefik.http.routers.vscode.entrypoints: http
      traefik.http.routers.vscode.rule: Host(`seat${SEAT_INDEX}.${DOMAIN?Environment variable DOMAIN is mandatory}`)
      traefik.http.routers.vscode.service: vscode
      traefik.http.routers.vscode.middlewares: redirect-to-https
      # Authenticated endpoint
      traefik.http.routers.vscode-s.entrypoints: https
      traefik.http.routers.vscode-s.rule: Host(`seat${SEAT_INDEX}.${DOMAIN?Environment variable DOMAIN is mandatory}`)
      traefik.http.routers.vscode-s.service: vscode
      traefik.http.routers.vscode-s.tls: "true"
