pipeline:
  build:
    image: docker:29.1.2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag registry:5000/groot/backend .
    - docker push registry:5000/groot/backend