services:

  grafana:
    image: grafana/grafana:12.0.1
    environment:
      GF_SECURITY_ADMIN_USER: seat
      GF_SECURITY_ADMIN_PASSWORD: "${SEAT_PASS:?You must supply SEAT_PASS}"
    labels:
      traefik.enable: "true"
      traefik.http.services.grafana.loadbalancer.server.port: 3000
      traefik.http.routers.grafana.entrypoints: http
      traefik.http.routers.grafana.rule: Host(`grafana.${DOMAIN:?You must supply DOMAIN}`) || Host(`grafana.${IP:?You must supply IP}.nip.io`)
      traefik.http.routers.grafana.service: grafana
